error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='虎口逃生', vod_tx_albumId='gudtw22rd4ws2dg', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/gudtw22rd4ws2dg1482820833/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='邓光荣,汤兰花,曹達華,', vod_director='唐基明', vod_writer='', vod_behind='', vod_tag='动作,惊悚', vod_blurb='美国唐人街由于越南难民的涌入，形势更加复杂。当局对此更为关注和恐惧，遂暗中策划"以华制华"政策。一日，的士司机关志华突遭越青帮袭击，关与同伙准备报仇。当他们赶至越青帮聚集地时，发现对方全已遭毒手。警方接报后将此地包围，关被当成凶手为警方通缉，他只好潜返香港暂避。美警方追至香港，关再陷杀机之中。关从律师口中得知此乃政治阴谋。由于关的机智勇猛，越青帮没能奈何他，却捉走他的妻儿作人质迫他投降。关在澳门与越青帮交换人质时爆发了一场血战，他虽救出了妻儿，但料到今后的日子仍将陷于荆棘之中。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700897', vod_duration='01:31:02', vod_year='1984', vod_status='0' where vod_iqiyi_albumId="gudtw22rd4ws2dg" or vod_douban_albumId="gudtw22rd4ws2dg" or vod_yk_albumId="gudtw22rd4ws2dg" or vod_tx_albumId="gudtw22rd4ws2dg" or vod_mango_albumId = "gudtw22rd4ws2dg"
(1292, "Truncated incorrect DOUBLE value: 'gudtw22rd4ws2dg'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='狙击目标', vod_tx_albumId='to7u94kyml1zcyi', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/to7u94kyml1zcyit1477058443.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='黎耀祥,车婉婉,王凯韦,梁鸿华,林伟贤,', vod_director='梁鸿华', vod_writer='', vod_behind='', vod_tag='动作,剧情', vod_blurb='古董商人李焕达遭遇交通意外,入院后昏迷不醒.李焕达唯一亲人,侄儿李文迪对这次意外表现得异常关心,他关心的只是叔父的遗产.当他发现他只是第二继承人的时候,他决定要让第一继承人在这个世上消失。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700897', vod_duration='01:23:00', vod_year='2003', vod_status='0' where vod_iqiyi_albumId="to7u94kyml1zcyi" or vod_douban_albumId="to7u94kyml1zcyi" or vod_yk_albumId="to7u94kyml1zcyi" or vod_tx_albumId="to7u94kyml1zcyi" or vod_mango_albumId = "to7u94kyml1zcyi"
(1292, "Truncated incorrect DOUBLE value: 'to7u94kyml1zcyi'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='回火', vod_tx_albumId='t02i8a6wcb2csea', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/t02i8a6wcb2csea1478679574/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='02', vod_sub='', vod_en='', vod_actor='威廉·鲍德温,罗伯特·德尼罗,库尔特·拉塞尔,唐纳德·萨瑟兰,', vod_director='朗·霍华德', vod_writer='', vod_behind='', vod_tag='动作,犯罪,剧情', vod_blurb='史蒂芬与布莱恩是一对来自救火世家的兄弟，史蒂芬继承父业投入救火工作，却因为工作的危险性与不安定性，与妻子的关系陷入困境。布莱恩因年幼时目睹父亲在救火时被烧死，而对救火工作又爱又惧。芝加哥市出现一名纵火犯，警局派出调查员唐纳追查嫌犯，而布莱恩充任其助手，深入火窟，并查处背后的真凶竟是....', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700897', vod_duration='02:17:16', vod_year='1991', vod_status='0' where vod_iqiyi_albumId="t02i8a6wcb2csea" or vod_douban_albumId="t02i8a6wcb2csea" or vod_yk_albumId="t02i8a6wcb2csea" or vod_tx_albumId="t02i8a6wcb2csea" or vod_mango_albumId = "t02i8a6wcb2csea"
(1292, "Truncated incorrect DOUBLE value: 't02i8a6wcb2csea'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='流星风暴', vod_tx_albumId='t8qs0r52udkckip', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/t8qs0r52udkckip1551328044/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='希瑞·J·威尔森,Peter LaCroix,Scott Hylands,Aaron Pearl,Desirée Loewen,', vod_director='Kristoffer Tabori', vod_writer='', vod_behind='', vod_tag='科幻,惊悚,动作,剧情', vod_blurb='安娜和杰克在科罗拉多的小镇过着美满和乐的家庭生活。可是死神的降临成了他们生命中最不幸的开端：他们最亲爱的儿子瑞克，在一次意外中丧失生命，原先美好平淡的生活一下子被巨大的阴影完全笼罩，杰克也一直沉溺在失去儿子的梦魇之中，久久无法振作苏醒…。
六个月后，他们决定离开这个令他们伤心欲绝的小镇，留下那些悲伤的记忆、忘记一切痛苦的回忆。然而这时，天空中却出现了不同于往常的异样景象，数以万计的彗星居然成了熊熊燃烧的巨大火球，热腾腾地冲向地球…。这回地球上所有的人类，该怎么面对这场狂暴的灾难？ ！', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700901', vod_duration='01:34:10', vod_year='2007', vod_status='0' where vod_iqiyi_albumId="t8qs0r52udkckip" or vod_douban_albumId="t8qs0r52udkckip" or vod_yk_albumId="t8qs0r52udkckip" or vod_tx_albumId="t8qs0r52udkckip" or vod_mango_albumId = "t8qs0r52udkckip"
(1292, "Truncated incorrect DOUBLE value: 't8qs0r52udkckip'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='城市飙女', vod_tx_albumId='2t043uuzavnvi4a', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/2t043uuzavnvi4a1548829974/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='阮市宣,田明,', vod_director='赖汶星', vod_writer='', vod_behind='', vod_tag='动作,剧情', vod_blurb='陋巷之狼又出现了，上头下令必需要立刻侦查，为了引色狼，某一女警扮小姐引色狼出来，好色的狼究竟能否抵挡美色的诱惑呢.......', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700901', vod_duration='01:22:49', vod_year='1980', vod_status='0' where vod_iqiyi_albumId="2t043uuzavnvi4a" or vod_douban_albumId="2t043uuzavnvi4a" or vod_yk_albumId="2t043uuzavnvi4a" or vod_tx_albumId="2t043uuzavnvi4a" or vod_mango_albumId = "2t043uuzavnvi4a"
(1292, "Truncated incorrect DOUBLE value: '2t043uuzavnvi4a'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='秘窗', vod_tx_albumId='5klwnx6ju03jpby', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/5klwnx6ju03jpbyt1444844469.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='约翰尼·德普,约翰·特托罗,玛丽亚·贝罗,蒂莫西·赫顿,', vod_director='大卫·凯普', vod_writer='', vod_behind='', vod_tag='悬疑,惊悚,动作', vod_blurb='雷尼（约翰尼·德普 Johnny Depp 饰）的妻子出了轨，他发现她和另一个男人躺在床上，他提出了离婚。然而，婚姻的阴影并没能使雷尼恢复原气。他的文笔开始暗淡无光，找不到从前的创作激情。于是，他来到了一个湖畔小屋疗伤创作。然而这个小屋，却给他带来了新的麻烦。
首先是一个陌生人的造访令他十分恼火。那人声称雷尼抄袭了他的作品，雷尼百般解释也不能让他信服。于是雷尼翻箱倒柜，想找出原稿，却发现原稿离奇失踪。惊悚事件陆续有来，整个小屋，好像出于某种危险的情势中，雷尼非常害怕，然而却查不出缘由。是不是前妻和她的情人在作怪？他们到底有何目的？然而，真相却让雷尼自己都不敢相信。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700901', vod_duration='01:35:55', vod_year='2004', vod_status='0' where vod_iqiyi_albumId="5klwnx6ju03jpby" or vod_douban_albumId="5klwnx6ju03jpby" or vod_yk_albumId="5klwnx6ju03jpby" or vod_tx_albumId="5klwnx6ju03jpby" or vod_mango_albumId = "5klwnx6ju03jpby"
(1292, "Truncated incorrect DOUBLE value: '5klwnx6ju03jpby'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='冲向天外天', vod_tx_albumId='cdmmiuj7exqi98s', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/cdmmiuj7exqi98st1444804530.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='伊桑·霍克,瑞弗·菲尼克斯,Bobby Fite,', vod_director='乔·丹特', vod_writer='', vod_behind='', vod_tag='冒险,奇幻,科幻,动作', vod_blurb='宾克蓝道是一个平凡的邻家少年，因为一场奇异的梦境而改变了他和另外两名少男（伍夫甘格、伍德斯）的一生、三名少年对外太空皆存有幻想与探险的渴望。当他们正在自家后院中著手探险的筹备工作时，一场出奇不意的事件就此展开，因为在遥远深邃的外太空中有个人早在那儿呼唤著，等待著他们...', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700901', vod_duration='01:49:14', vod_year='1985', vod_status='0' where vod_iqiyi_albumId="cdmmiuj7exqi98s" or vod_douban_albumId="cdmmiuj7exqi98s" or vod_yk_albumId="cdmmiuj7exqi98s" or vod_tx_albumId="cdmmiuj7exqi98s" or vod_mango_albumId = "cdmmiuj7exqi98s"
(1292, "Truncated incorrect DOUBLE value: 'cdmmiuj7exqi98s'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='烈日迷踪', vod_tx_albumId='klrf6mxat5fqqj5', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/klrf6mxat5fqqj5t1464912111.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='乔什·杜哈明,乔什·维金斯,琳恩·柯林斯,艾玛·福尔曼,', vod_director='特雷·尼尔森', vod_writer='', vod_behind='', vod_tag='剧情,动作', vod_blurb='故事讲述了约翰（乔什·杜哈明 Josh Duhamel 饰），一名时运不济的小骗子，偶然地得到了路易斯（乔什·维金斯 Josh Wiggins 饰），一个刚刚成为孤儿的小男孩的帮助，他们组成了搭档，在前往路易斯外婆家的旅途中建立起了一种强大的羁绊……', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700901', vod_duration='01:33:07', vod_year='2015', vod_status='0' where vod_iqiyi_albumId="klrf6mxat5fqqj5" or vod_douban_albumId="klrf6mxat5fqqj5" or vod_yk_albumId="klrf6mxat5fqqj5" or vod_tx_albumId="klrf6mxat5fqqj5" or vod_mango_albumId = "klrf6mxat5fqqj5"
(1292, "Truncated incorrect DOUBLE value: 'klrf6mxat5fqqj5'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='乐高®DC超级英雄美少女：失忆大冒险', vod_tx_albumId='3ewxwcf28anptwy', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/3ewxwcf28anptwy1505456780/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='1', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='', vod_director='Todd Grimes', vod_writer='', vod_behind='', vod_tag='动画,动作,家庭', vod_blurb='DC超级女孩去乐高在这个充满惊险的世界动画冒险！惊险游戏只有在超女、神奇女侠和巴特女孩都不记得他们所犯下的一系列错误时才开始。当连大黄蜂、武士刀和其他超级英雄高的成员都不怀好意的时候，女孩们又能求助于谁呢？要解开这种心理混乱，找出这些错误行为背后是谁，起来，穿上你的斗篷，为乐高女孩的终极力量！', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700913', vod_duration='01:12:13', vod_year='2017', vod_status='0' where vod_iqiyi_albumId="3ewxwcf28anptwy" or vod_douban_albumId="3ewxwcf28anptwy" or vod_yk_albumId="3ewxwcf28anptwy" or vod_tx_albumId="3ewxwcf28anptwy" or vod_mango_albumId = "3ewxwcf28anptwy"
(1292, "Truncated incorrect DOUBLE value: '3ewxwcf28anptwy'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='祖鲁战争', vod_tx_albumId='525gpg6ru7xo1th', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/525gpg6ru7xo1th1550559406/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='02', vod_sub='', vod_en='', vod_actor='斯坦利·贝克,杰克·霍金斯,厄拉·亚科布松,迈克尔·凯恩,', vod_director='赛·恩菲尔德', vod_writer='', vod_behind='', vod_tag='动作,冒险,剧情', vod_blurb='本片讲述19世纪末英军在非洲的一处要塞人手不足，但遭到成千上万当地土著祖鲁人的进攻。祖鲁族是非洲最善战的民族，与英军发生激烈交战。英军顽强抵抗，最终以小胜大。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700913', vod_duration='02:13:49', vod_year='1964', vod_status='0' where vod_iqiyi_albumId="525gpg6ru7xo1th" or vod_douban_albumId="525gpg6ru7xo1th" or vod_yk_albumId="525gpg6ru7xo1th" or vod_tx_albumId="525gpg6ru7xo1th" or vod_mango_albumId = "525gpg6ru7xo1th"
(1292, "Truncated incorrect DOUBLE value: '525gpg6ru7xo1th'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='狂野之河', vod_tx_albumId='reti6h2xw5bxbv1', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/reti6h2xw5bxbv11525415245/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='梅丽尔·斯特里普,凯文·贝肯,大卫·斯特雷泽恩,约翰·C·赖利,', vod_director='柯蒂斯·汉森', vod_writer='', vod_behind='', vod_tag='动作,冒险,犯罪,惊悚', vod_blurb='Tom（大卫·斯特雷泽恩 David Strathairn  饰）和Gail（梅丽尔·斯特里普 Meryl Streep  饰）夫妻感情疏远，为了努力弥补缝隙，他们决定带着儿子Roarke（约瑟夫·梅泽罗 Joseph Mazzello 饰）和爱狗进行漂流冒险旅行——Gail曾经勇敢地漂流过铁手套这一令人闻风丧胆的三河交汇处。
途中他们遇见Wade（凯文·贝肯 Kevin Bacon 饰）、Terry（约翰·C·赖利 John C. Reilly  饰）和Frank，Wade的小手段让Roarke将他推崇为英雄。然而Frank中途无端失踪，突然Wade和Terry露出狰狞的真面目——他们是抢劫巨款潜逃的罪犯，正在逃亡。
Wade利用Tom和Roarke做人质，威胁Gail带他们漂过铁手套。Tom在误打误撞中逃离虎口，和爱狗在下游准备埋伏，勇敢的Gail将第二次挑战铁手套，而且是要救出儿子。早在下游等待的Tom和Gail合力，不仅是战斗，还是再次感受到同甘共苦的爱情。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700913', vod_duration='01:51:13', vod_year='1994', vod_status='0' where vod_iqiyi_albumId="reti6h2xw5bxbv1" or vod_douban_albumId="reti6h2xw5bxbv1" or vod_yk_albumId="reti6h2xw5bxbv1" or vod_tx_albumId="reti6h2xw5bxbv1" or vod_mango_albumId = "reti6h2xw5bxbv1"
(1292, "Truncated incorrect DOUBLE value: 'reti6h2xw5bxbv1'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='幸福之钟', vod_tx_albumId='5umhqlye0mosd48', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/5umhqlye0mosd481527154214/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='寺岛进,西田尚美,板尾创路,筱原凉子,白川和子,', vod_director='萨布', vod_writer='', vod_behind='', vod_tag='动作,喜剧,剧情', vod_blurb='工厂倒闭，失业的五十岚（寺岛进饰）心情低落地走在路上，见到了形形色色的人们：企业倒闭集会示威自残的工人、打算捐器官做善意但却遭砍身亡的黑帮老大、妻子外遇自己身处狱中的可怜男子、孩子身陷火场的单身漂亮母亲（筱原凉子饰）、中了六合彩但心脏病发身亡的老人、失业自杀的中年男子、腰缠万贯但身患绝症的男人。而五十岚也经历了大喜大落，面对的人一变再变，每个人都和他倾诉遭遇，而他一言不发地倾听着。
后来他碰上一件怪事，第二天回到家中，妻子（西田尚美饰）正在等着他回来。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700917', vod_duration='01:27:46', vod_year='2002', vod_status='0' where vod_iqiyi_albumId="5umhqlye0mosd48" or vod_douban_albumId="5umhqlye0mosd48" or vod_yk_albumId="5umhqlye0mosd48" or vod_tx_albumId="5umhqlye0mosd48" or vod_mango_albumId = "5umhqlye0mosd48"
(1292, "Truncated incorrect DOUBLE value: '5umhqlye0mosd48'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='大汉风之入关之约', vod_tx_albumId='o2yf54wlkc0i4fi', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/o2yf54wlkc0i4fi1573023676/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='胡军,吴倩莲,肖荣生,王刚,吴樾,', vod_director='卫翰韬', vod_writer='', vod_behind='', vod_tag='历史,古装,战争,动作,剧情', vod_blurb='公元前210年，秦始皇重疾而亡。第十八子胡亥被宦官赵高扶上帝位后骄奢淫逸、不理朝政，致使秦国大权被赵高所操持。秦始皇的暴毙而亡加上胡亥的昏庸无道，让天下的反秦力量日益高涨。这其中，楚国将门后裔项梁、项羽叔侄二人的力量最为强大，以至于让在沛县起义的刘邦也率众投奔而来。然而，随着楚国实力的不断雄厚，尤其是项梁在定陶一战中被秦国守将章邯击毙后，楚国内部发生了重大的变化。为了收拢人心、整顿秩序，以期早日实现入主关中的夙愿，楚怀王对已经形成气候的刘邦和项羽是利用有加但又戒备三分。项梁战死后，楚怀王犒赏三军，封刘邦为武安侯，封项羽为长安侯，并在龙案前殿立下盟约，谁先入主关中、拿下咸阳，就封谁为关中之王。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700917', vod_duration='01:28:20', vod_year='2005', vod_status='0' where vod_iqiyi_albumId="o2yf54wlkc0i4fi" or vod_douban_albumId="o2yf54wlkc0i4fi" or vod_yk_albumId="o2yf54wlkc0i4fi" or vod_tx_albumId="o2yf54wlkc0i4fi" or vod_mango_albumId = "o2yf54wlkc0i4fi"
(1292, "Truncated incorrect DOUBLE value: 'o2yf54wlkc0i4fi'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='超级霸王2', vod_tx_albumId='85l77yd86tvcwjn', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/85l77yd86tvcwjnt1445570959.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='杨斯,威廉·泽布卡,迈克·贝尔纳多,', vod_director='保罗·泽勒', vod_writer='', vod_behind='', vod_tag='动作', vod_blurb='影片讲述大佬史达是拉斯维加斯地下死亡擂台的幕后黑手，为满足有钱人的感官刺激，擂台上机关满布，凡踏上去比赛的人只有一个选择——非生即死！警长乐年为了捣毁史达巢穴，只好以其人之道还治其人之身，与黑道小辈艾迪和格斗之王薛高合作，挑选了四个跷勇无比的人，训练为最强的格斗士，以血和生命作代价，誓将史达等人一网打尽。', vod_remarks='', vod_pubdate='', vod_total='2', vod_is_from='1', vod_time_up='1599700917', vod_duration='01:22:21', vod_year='1996', vod_status='0' where vod_iqiyi_albumId="85l77yd86tvcwjn" or vod_douban_albumId="85l77yd86tvcwjn" or vod_yk_albumId="85l77yd86tvcwjn" or vod_tx_albumId="85l77yd86tvcwjn" or vod_mango_albumId = "85l77yd86tvcwjn"
(1292, "Truncated incorrect DOUBLE value: '85l77yd86tvcwjn'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='浴血战士', vod_tx_albumId='ygfgeicgvrfsw9v', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/ygfgeicgvrfsw9vt1476932474.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='02', vod_sub='', vod_en='', vod_actor='盖瑞·丹尼尔斯,Mike Norris,Bentley Mitchum,约翰·里斯-戴维斯,Zeev Revach,', vod_director='约瑟夫·齐托', vod_writer='', vod_behind='', vod_tag='动作', vod_blurb='一个国际维和部队试图保持两个中东国家之间的关系，从爆炸到公开战争。当一个巡逻兵消失在沙漠中，一群来自不同国家的士兵被扔在一起去寻找他们。在被一些阿拉伯士兵开枪后，巡逻队发现，其中一个已经走私了核武器，并计划用它来带来战斗到它的最终目的。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700916', vod_duration='02:03:46', vod_year='1999', vod_status='0' where vod_iqiyi_albumId="ygfgeicgvrfsw9v" or vod_douban_albumId="ygfgeicgvrfsw9v" or vod_yk_albumId="ygfgeicgvrfsw9v" or vod_tx_albumId="ygfgeicgvrfsw9v" or vod_mango_albumId = "ygfgeicgvrfsw9v"
(1292, "Truncated incorrect DOUBLE value: 'ygfgeicgvrfsw9v'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='自由斗士：射线', vod_tx_albumId='mzc002008ii4dkz', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/mzc002008ii4dkz1599120199534/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='1', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='', vod_director='伊桑·斯波尔丁', vod_writer='', vod_behind='', vod_tag='动画,动作,奇幻', vod_blurb='该剧改编自DC漫画，讲述雷蒙德·雷·特里尔运用光能维护正义的故事。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700916', vod_duration='01:10:06', vod_year='2018', vod_status='0' where vod_iqiyi_albumId="mzc002008ii4dkz" or vod_douban_albumId="mzc002008ii4dkz" or vod_yk_albumId="mzc002008ii4dkz" or vod_tx_albumId="mzc002008ii4dkz" or vod_mango_albumId = "mzc002008ii4dkz"
(1292, "Truncated incorrect DOUBLE value: 'mzc002008ii4dkz'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='横行天下', vod_tx_albumId='6r0jiwpt1569nnl', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/6r0jiwpt1569nnl1516073001/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='查克·诺瑞斯,小路易斯·格赛特,梅乐蒂·安德森,威尔·萨姆森,', vod_director='J·李·汤普森', vod_writer='', vod_behind='', vod_tag='动作,冒险,喜剧', vod_blurb='麦斯（查克·诺瑞斯 饰）和李奥（小路易斯·格赛特 饰）是一对即将退休的佣兵，然而就在他们碰到一位身怀藏宝图的美女时，人生却有了意外的转折。这对哥俩好怀抱着挖宝的美梦，踏上一段有如云霄飞车般刺激的冒险旅程，从亚马逊山中的失落古庙一路追寻到危地马拉的丛林。他们在途中碰到一队不友善的外国佣兵、噬血的鳄鱼，以及深怕他们想偷走祖传宝藏，一心置他们于死地的印第安祭司后代。他们必须突破重重危险，破解致命的咒语，才有机会抱得宝藏归。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700928', vod_duration='01:40:41', vod_year='1986', vod_status='0' where vod_iqiyi_albumId="6r0jiwpt1569nnl" or vod_douban_albumId="6r0jiwpt1569nnl" or vod_yk_albumId="6r0jiwpt1569nnl" or vod_tx_albumId="6r0jiwpt1569nnl" or vod_mango_albumId = "6r0jiwpt1569nnl"
(1292, "Truncated incorrect DOUBLE value: '6r0jiwpt1569nnl'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='血海翻天', vod_tx_albumId='d6rv9icfrsj6bz9', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/d6rv9icfrsj6bz9t1444813216.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='帕特里克·斯威兹,连姆·尼森,亚当·鲍德温,', vod_director='约翰·伊文', vod_writer='', vod_behind='', vod_tag='犯罪,动作,惊悚', vod_blurb='芝加哥当地的黑手党想称霸当地所有的生意买卖，他们为达目的不择手段，甚至牺牲人命也在所不惜，当他发现自己的亲人死于非命时，他决心与黑手党抗衡到底！', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700928', vod_duration='01:48:16', vod_year='1989', vod_status='0' where vod_iqiyi_albumId="d6rv9icfrsj6bz9" or vod_douban_albumId="d6rv9icfrsj6bz9" or vod_yk_albumId="d6rv9icfrsj6bz9" or vod_tx_albumId="d6rv9icfrsj6bz9" or vod_mango_albumId = "d6rv9icfrsj6bz9"
(1292, "Truncated incorrect DOUBLE value: 'd6rv9icfrsj6bz9'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='末路狂奔', vod_tx_albumId='h3iwot6xumfgrmu', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/h3iwot6xumfgrmut1444854269.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='理查德·柯伊尔,布隆森·韦伯,阿格妮丝·迪恩,', vod_director='路易斯·普瑞托', vod_writer='', vod_behind='', vod_tag='犯罪,惊悚,动作', vod_blurb='一名黑道混混在毒品交易中失利，因走投无路而逃亡，他的女友在关键时刻背叛他。他从监狱里被释放后，想要重新做人，但困难重重。导演透过三个人物的命运，描绘出哥本哈根黑道贩毒界内阴暗和激动人心的一面。三个人物的命运悲怆感人，他们的生活方式掩盖了其内心深处的创伤。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700928', vod_duration='01:27:31', vod_year='2012', vod_status='0' where vod_iqiyi_albumId="h3iwot6xumfgrmu" or vod_douban_albumId="h3iwot6xumfgrmu" or vod_yk_albumId="h3iwot6xumfgrmu" or vod_tx_albumId="h3iwot6xumfgrmu" or vod_mango_albumId = "h3iwot6xumfgrmu"
(1292, "Truncated incorrect DOUBLE value: 'h3iwot6xumfgrmu'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='太阳风暴', vod_tx_albumId='omaqw9q9ursnivt', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/omaqw9q9ursnivt1550209766/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='波·德瑞克,斯泰西·基齐,', vod_director='Mike Marvin', vod_writer='', vod_behind='', vod_tag='动作,剧情', vod_blurb='当将军在圣胡安的街道上被刺杀后，他的四个女儿聚拢来聆听他的遗嘱。每个人都希望继承他的财产，不幸的是，漂亮而残忍的头目领导的凶手也有同样的意图，姐妹们必须相互依靠保全她们的性命，但是除了赌博，似乎将军还牵扯到很多事情，他把他的女儿们带进了跟中央情报局和美国财政局有关的纠纷中…', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700932', vod_duration='01:27:28', vod_year='2007', vod_status='0' where vod_iqiyi_albumId="omaqw9q9ursnivt" or vod_douban_albumId="omaqw9q9ursnivt" or vod_yk_albumId="omaqw9q9ursnivt" or vod_tx_albumId="omaqw9q9ursnivt" or vod_mango_albumId = "omaqw9q9ursnivt"
(1292, "Truncated incorrect DOUBLE value: 'omaqw9q9ursnivt'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='同闯歌坛', vod_tx_albumId='3hlnne8ml71on72', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/3hlnne8ml71on721542188758/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='郑则仕,廖伟雄,司马燕,金燕玲,', vod_director='赖建国', vod_writer='', vod_behind='', vod_tag='爱情,动作,剧情', vod_blurb='任剑飞自小丧父，母亲全靠亡夫之弟任坤帮助，始能维持生计。坤疼爱侄儿飞，处处呵护备至。飞自小热爱唱歌，坤为完飞之歌星梦，暗中动用毕生积蓄助飞灌录唱片，坤更在自己工作的唱片店为飞宣传。坤更因此而被开除。一天，飞应征酒廊歌手，但此职位已被样子甜美的白咏仙夺得，飞对白一见钟情，甘愿在酒廊当侍应。后来，酒廊经理知悉飞歌喉不俗，便请飞在酒廊试唱。飞初试啼声失准，又与调戏白的酒客龃龉，飞差点与酒客大打出手。幸得坤及时赶到调停，坤更暗中帮助飞继续留在酒廊表演。然而，飞对坤有所误会，处处与坤作对。更在母亲生日饭餐中，当众辱骂坤，使坤十分难堪。幸得母亲狠狠地教训一顿，飞始知错怪了坤。最后，飞向坤道歉，两叔侄和好如初。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700932', vod_duration='01:30:55', vod_year='1983', vod_status='0' where vod_iqiyi_albumId="3hlnne8ml71on72" or vod_douban_albumId="3hlnne8ml71on72" or vod_yk_albumId="3hlnne8ml71on72" or vod_tx_albumId="3hlnne8ml71on72" or vod_mango_albumId = "3hlnne8ml71on72"
(1292, "Truncated incorrect DOUBLE value: '3hlnne8ml71on72'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='一起飞', vod_tx_albumId='xy700r7gi2yxthv', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/xy700r7gi2yxthvt1444939138.jpg/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='林志颖,张娜拉,万思维,', vod_director='吴迪', vod_writer='', vod_behind='', vod_tag='喜剧,动作,院线,爱情,奇幻,冒险', vod_blurb='　“苍狼”特警队在原始森林中展开大搜捕；一支神秘队伍在森林中前行。他们的目标似乎都是“劫匪”许逸凡和“受害人”何芊芊。 
　　特种兵出身的许逸凡让阅历不丰的何芊芊第一次感受到天下竟有和自己男友萧寒截然不同的男人。凭着许逸凡特种兵的经验，他们最终克服艰难险阻，走出了原始森林，但却与“呆哥”遭遇而大展拳脚，最终被“苍狼”特警队俘获。 
　　何芊芊的男友萧寒长相俊帅，学识渊博，深得何芊芊喜爱和爸爸何振雄的赏识，被安排在何振雄公司做副总。看着爸爸的身体愈来愈不好，何芊芊按照与爸爸签订的“合约”，还是决定与聚少离多的萧寒结婚，以了却爸爸的心思。然而，许逸凡的出现，完全打乱了这对恋人的生活。 
　　林雨馨经何芊芊的挽留，也来到了何家暂住。当晚的一场化妆PARTY，让苦苦寻找男友的林雨馨有了重大发现。第二天，林雨馨不辞而别。 
　　一宗扑朔迷离的奇案发生了，是情杀，还是劫持？伴随着案件的侦破，一段生离死别的奇缘揭开了！', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700932', vod_duration='01:34:20', vod_year='2012', vod_status='0' where vod_iqiyi_albumId="xy700r7gi2yxthv" or vod_douban_albumId="xy700r7gi2yxthv" or vod_yk_albumId="xy700r7gi2yxthv" or vod_tx_albumId="xy700r7gi2yxthv" or vod_mango_albumId = "xy700r7gi2yxthv"
(1292, "Truncated incorrect DOUBLE value: 'xy700r7gi2yxthv'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='复仇的怒火', vod_tx_albumId='i9q0ov64uyphpba', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/i9q0ov64uyphpba1515997340/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='Olivier Gruner,John Ritter,Robert Culp,', vod_director='Avi Nesher', vod_writer='', vod_behind='', vod_tag='动作', vod_blurb='商业钜子乔纳斯原本与妻子过著富有、安逸的生活，孰料被卷进一场恐怖份子的杀戮行动中。痛失爱妻、身心受创的乔纳斯生活从此脱轨，并深陷于悲伤中，且日渐把内心的悲痛转化成无法遏止的愤怒。为了报妻子惨死的仇恨，他开出二百万的高价，雇用了以代号“老鹰“为首的魔鬼佣兵团来追踪凶手的下落，这笔交易唯一的条件是他要与魔鬼佣兵们一起执行任务。', vod_remarks='', vod_pubdate='', vod_total='2', vod_is_from='1', vod_time_up='1599700932', vod_duration='01:35:00', vod_year='1997', vod_status='0' where vod_iqiyi_albumId="i9q0ov64uyphpba" or vod_douban_albumId="i9q0ov64uyphpba" or vod_yk_albumId="i9q0ov64uyphpba" or vod_tx_albumId="i9q0ov64uyphpba" or vod_mango_albumId = "i9q0ov64uyphpba"
(1292, "Truncated incorrect DOUBLE value: 'i9q0ov64uyphpba'")
error>>>>>>>update iqy_vod set type_pid='1', type_id='6', vod_name='梁天来', vod_tx_albumId='svfrp2bjseljv5o', vod_pic='http://puui.qpic.cn/vcover_vt_pic/0/svfrp2bjseljv5o1548831337/220', vod_pic_thumb='', vod_pic_slide='', vod_tv='', vod_weekday='', vod_area='', vod_version='', vod_state='1', vod_is_pay_mark='1', vod_is_advance='0', vod_isend='1', vod_serial='01', vod_sub='', vod_en='', vod_actor='伍卫国,卢国雄,梁天,顾冠忠,', vod_director='王风', vod_writer='', vod_behind='', vod_tag='剧情,动作', vod_blurb='一句"又是官"包含多少无奈与辛酸，最终还是要靠元魂索命帮助御状，还是靠清"官"两广总督帮助沉冤得雪。', vod_remarks='', vod_pubdate='', vod_total='1', vod_is_from='1', vod_time_up='1599700932', vod_duration='01:36:42', vod_year='1979', vod_status='0' where vod_iqiyi_albumId="svfrp2bjseljv5o" or vod_douban_albumId="svfrp2bjseljv5o" or vod_yk_albumId="svfrp2bjseljv5o" or vod_tx_albumId="svfrp2bjseljv5o" or vod_mango_albumId = "svfrp2bjseljv5o"
(1292, "Truncated incorrect DOUBLE value: 'svfrp2bjseljv5o'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
error>>>>>>>select id, vod_name from iqy_vod_collection_json where None
(1054, "Unknown column 'vod_name' in 'field list'")
